package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table APPS.
 */
public class Apps implements java.io.Serializable {

    private Long id;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String package_name;
    private long package_size;
    private java.util.Date install_time;
    private Boolean system_app;
    private Boolean favorite;
    private java.util.Date favorite_added_time;
    private Boolean delete;
    private java.util.Date deleted_time;

    public Apps() {
    }

    public Apps(Long id) {
        this.id = id;
    }

    public Apps(Long id, String name, String package_name, long package_size, java.util.Date install_time, Boolean system_app, Boolean favorite, java.util.Date favorite_added_time, Boolean delete, java.util.Date deleted_time) {
        this.id = id;
        this.name = name;
        this.package_name = package_name;
        this.package_size = package_size;
        this.install_time = install_time;
        this.system_app = system_app;
        this.favorite = favorite;
        this.favorite_added_time = favorite_added_time;
        this.delete = delete;
        this.deleted_time = deleted_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getPackage_name() {
        return package_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPackage_name(String package_name) {
        this.package_name = package_name;
    }

    public long getPackage_size() {
        return package_size;
    }

    public void setPackage_size(long package_size) {
        this.package_size = package_size;
    }

    public java.util.Date getInstall_time() {
        return install_time;
    }

    public void setInstall_time(java.util.Date install_time) {
        this.install_time = install_time;
    }

    public Boolean getSystem_app() {
        return system_app;
    }

    public void setSystem_app(Boolean system_app) {
        this.system_app = system_app;
    }

    public Boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(Boolean favorite) {
        this.favorite = favorite;
    }

    public java.util.Date getFavorite_added_time() {
        return favorite_added_time;
    }

    public void setFavorite_added_time(java.util.Date favorite_added_time) {
        this.favorite_added_time = favorite_added_time;
    }

    public Boolean getDelete() {
        return delete;
    }

    public void setDelete(Boolean delete) {
        this.delete = delete;
    }

    public java.util.Date getDeleted_time() {
        return deleted_time;
    }

    public void setDeleted_time(java.util.Date deleted_time) {
        this.deleted_time = deleted_time;
    }

}
