package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Apps;

import greendao.AppsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appsDaoConfig;

    private final AppsDao appsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appsDaoConfig = daoConfigMap.get(AppsDao.class).clone();
        appsDaoConfig.initIdentityScope(type);

        appsDao = new AppsDao(appsDaoConfig, this);

        registerDao(Apps.class, appsDao);
    }
    
    public void clear() {
        appsDaoConfig.getIdentityScope().clear();
    }

    public AppsDao getAppsDao() {
        return appsDao;
    }

}
